name: Apprise
package: community.lazycat.app.apprise
version: 1.3.1
min_os_version: 1.3.8
description: "Apprise - Push Notifications that work with just about every platform"
license: MIT
homepage: https://github.com/caronc/apprise
author: Chris Caron

application:
  subdomain: apprise
  upstreams:
    - location: /
      backend: http://apprise:8000/
  public_path:
    - /

services:
  apprise:
    # caronc/apprise:v1.3.1
    image: docker.1ms.run/caronc/apprise:v1.3.1
    environment:
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_WORKER_COUNT={{.U.worker_count}}
      - APPRISE_ADMIN={{.U.enable_admin}}
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/plugin:/plugin
      - /lzcapp/var/attach:/attach

locales:
  en:
    name: "Apprise"
    description: "Push Notifications that work with just about every platform"
  zh:
    name: "Apprise"
    description: "支持几乎所有平台的推送通知服务"
