application:
  subdomain: apprise
  upstreams:
    - location: /
      backend: http://apprise:8000/
  public_path:
    - /
services:
  apprise:
    # upstream: caronc/apprise:2.0.1
    image: docker.1ms.run/caronc/apprise:2.0.1
    environment:
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_WORKER_COUNT={{.U.worker_count}}
      - APPRISE_ADMIN={{.U.enable_admin}}
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/plugin:/plugin
      - /lzcapp/var/attach:/attach
